### ISSUE TITLE
Change background for affiliations and contributors?

### ISSUE THREAD

**Issue by supernord** [ELIXIR-Belgium/elixir-toolkit-theme#173]
The affiliation and contributor boxes that the ETT renders appear to have a set background colour (see example below). This will sometimes clash with logos that have a different background. 

Maybe the boxes could have a transparent background? 

<img width="375" alt="image" src="https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/assets/50811354/b9b0e72b-7821-4cc7-98bd-e1b61ffe318a">

**Comment by bedroesb** [comment]
Hello @supernord, thanks for the feedback. Out of experience, if a logo has a background, it is white because of a png they got somewhere (and if it is a different background than white, it most of the time is because they screen-shotted it instead of saving). So if I make it transparent, it will be gray like the whole box, and than those white background logo's will pop out compared to the other ones. The idea is also that they look clickable :) Hope this does answer some things!

**Comment by bedroesb** [comment]
lets have a look, originally I wanted to have the same look as contributors:

file:///home/bedro/Pictures/Screenshots/Screenshot%20from%202023-06-13%2009-57-24.png
file:///home/bedro/Pictures/Screenshots/Screenshot%20from%202023-06-13%2009-57-20.png

**Comment by bedroesb** [comment]
I think taking the background color away for affiliations might actually help in the infectious disease toolkit. There the affiliations are about the workflow described, and not about the contributors of the page. Making it look different from the contributors will already help with that!
