### ISSUE TITLE
tools tagging queries

### ISSUE THREAD

**Issue by mshadbolt** [ELIXIR-Belgium/elixir-toolkit-theme#186]
Hello again!

I have started attempting to implement the super cool new tool tagging feature and tools and resources table but it isn't behaving the way that I expected. 

The tagging works well, example: 
https://australianbiocommons.github.io/human-omics-data-sharing-field-guide/other_repositories

I thought that when I tagged a tool that there would be a tools table that appeared at the bottom as is mentioned on this PR: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/127 

Tools table here: https://australianbiocommons.github.io/human-omics-data-sharing-field-guide/tools_resources

I was also expecting that, each time I tagged a tool on a particular page, it would automatically get added to the 'related pages' column of the larger tool table, but it is totally blank.

Not sure if what I am expecting is incorrect or if there are particular options I need to configure in order to get to the expected behaviour.

Thanks for any help you can offer!

**Comment by bedroesb** [comment]
@mshadbolt super cool you got this far, you are the first one to try out the tools function on their own, so thanks a lot for this feedback. Your expectations are fully correct, the only thing I see missing on first sight (I know it is not described in the documentation, will add it now!) is a  `page_id` in the frontmatter of the markdown pages. These are used to filter the tools + to tag the tools with the page id. I would suggest that if you use the `{% tool "tool-id" %}` snippet, that you do not use the `related_pages` metadata block in the main tools yaml file. because it will get overwritten with the tools mentioned in the markdown.

**Comment by mshadbolt** [comment]
Awesome, thanks @bedroesb, I have tested it out and it works perfectly once I add the `page-id` to the yamls on those pages.

I made a PR that adds the ability to have publications attached to tools, we would love this feature so would be great to see it as part of an upcoming release.

Thanks again for your help and ongoing updates of the cool theme!
