### ISSUE TITLE
Configuring image name for main-logo

### ISSUE THREAD

**Issue by mshadbolt** [ELIXIR-Belgium/elixir-toolkit-theme#64]
Hi there,

Thanks for the cool theme

I wanted to check whether it is possible to configure the filename that is used for the main_logo image? It seems like at the moment it is hard coded to be `/REPO_NAME/assets/img/main_logo.svg`, however I'd like to use a png so this doesn't work. Let me know if there is a way to configure it in the `_config.yml` for example.

A side question is whether there is a way you'd like it acknowledged that we are using this theme at all?

Thanks!

**Comment by bedroesb** [comment]
Cool to hear there is interest in this theme from outside! 
You are correct and this is a limitation. Making this configurable in the _config.yaml makes sense. Besides that I do recommend SVG's for scalability. 

We have a [badge](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme#attribution) that you can use in the README, and otherwise I can also just add you to the list in the README of this repo. You are fully free in this since the whole project is under MIT license :)

I am at the moment working on some real documentation because there is still just a backbone at the moment. This is example should serve as the minimum you need to use the theme: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme-example

**Comment by bedroesb** [comment]
I made implemented the feature in the linked pull request, you can test it out by using `custom-main-logo` as version for the theme in the _config.yml file. Since you are using an older version it is possible some of the scss variables changed.

**Comment by bedroesb** [comment]
if this works for you I will merge my pull request and release a new version

**Comment by supernord** [comment]
I tried this modification as well, and it works with a `main_logo.png`
https://australianbiocommons.github.io/how-to-guides/

Thanks @bedroesb
